use serde::{Deserialize, Serialize};
use std::fs;
use std::path::Path;
use std::time::{SystemTime, UNIX_EPOCH};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DatabaseRecord {
    pub id: String,
    pub name: String,
    pub engine: String, // "mysql", "mariadb", "sqlite", "postgres"
    pub username: String,
    pub password: Option<String>,
    pub host: String,
    pub collation: String,
    pub site: Option<String>,
    pub size_bytes: u64,
    pub created_at: u64,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct DatabaseStorage {
    pub databases: Vec<DatabaseRecord>,
}

impl DatabaseStorage {
    pub fn load_or_default(path: &str) -> Self {
        if Path::new(path).exists() {
            match fs::read_to_string(path) {
                Ok(content) => serde_json::from_str(&content).unwrap_or_default(),
                Err(_) => Self::default(),
            }
        } else {
            Self::default()
        }
    }

    pub fn save(&self, path: &str) -> std::io::Result<()> {
        if let Some(parent) = Path::new(path).parent() {
            let _ = fs::create_dir_all(parent);
        }
        let json = serde_json::to_string_pretty(self)
            .map_err(|e| std::io::Error::new(std::io::ErrorKind::InvalidData, e))?;
        fs::write(path, json)
    }

    pub fn list(&self) -> &[DatabaseRecord] {
        &self.databases
    }

    pub fn add(&mut self, record: DatabaseRecord) -> Result<(), String> {
        let name_trimmed = record.name.trim();
        if name_trimmed.is_empty() {
            return Err("Database name cannot be empty".to_string());
        }

        if self
            .databases
            .iter()
            .any(|d| d.name.eq_ignore_ascii_case(name_trimmed))
        {
            return Err(format!("Database '{name_trimmed}' already exists"));
        }

        self.databases.push(record);
        Ok(())
    }

    pub fn delete(&mut self, name: &str) -> bool {
        let initial_len = self.databases.len();
        self.databases
            .retain(|d| !d.name.eq_ignore_ascii_case(name));
        self.databases.len() < initial_len
    }

    pub fn find(&self, name: &str) -> Option<&DatabaseRecord> {
        self.databases
            .iter()
            .find(|d| d.name.eq_ignore_ascii_case(name))
    }

    pub fn generate_dump(&self, name: &str) -> Result<String, String> {
        let db = match self.find(name) {
            Some(d) => d,
            None => return Err(format!("Database '{name}' not found")),
        };

        let now = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map(|d| d.as_secs())
            .unwrap_or(0);

        let dump = format!(
            "-- ZPanl Sovereign Database Dump\n\
             -- Database: `{}`\n\
             -- Engine: {}\n\
             -- Host: {}\n\
             -- Timestamp: {}\n\
             -- Generated by ZPanl Pure Rust Web Management\n\n\
             SET FOREIGN_KEY_CHECKS=0;\n\
             SET SQL_MODE = \"NO_AUTO_VALUE_ON_ZERO\";\n\
             START TRANSACTION;\n\
             SET time_zone = \"+00:00\";\n\n\
             CREATE DATABASE IF NOT EXISTS `{}` DEFAULT CHARACTER SET {} COLLATE {};\n\
             USE `{}`;\n\n\
             -- Dump completed\n\
             COMMIT;\n",
            db.name,
            db.engine,
            db.host,
            now,
            db.name,
            if db.collation.starts_with("utf8mb4") {
                "utf8mb4"
            } else {
                "utf8"
            },
            db.collation,
            db.name
        );

        Ok(dump)
    }
}
